# Non Graded Chalenge Linear Algebra 2

Muhammad Farhan Zahirsyah

Batch 10

---
## Assignment Instructions

- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$



## Import library

In [18]:
import numpy as np

## 1. Membuat Tensor

In [19]:
tensor = np.array([  [[23,50],[7,12]],
                    [[57,67],[99,43]],
                    [[75,21],[57,12]],
                    [[87,26],[18,84]]
                ])

tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

## 2. Perkalian Matriks

In [20]:
a = np.array(
    [[23,50,19],[7,12,109],[57,67,98]]
)
b = np.array([17,22,19])

In [21]:
a @ b

array([1852, 2454, 4305])

## 3. Melakukan operasi Transpose, determinan, dan inverse 

In [22]:
matrix = np.array(
    [[23,50,19],[7,12,109],[57,67,98]]
)

In [23]:
matrix.transpose()

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [24]:
np.linalg.det(matrix)

131344.0000000002

In [25]:
np.linalg.inv(matrix)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])