# eigen vektor  dan value

In [2]:
import numpy as np

Linear transformation

eigen vektor yaitu 
matriks dikalikan dengan voktor menghasilkan kelipatan dari vektor

kelipatannya eigen value. 

nilai kelipatannya = si lambda = eigen value. 

In [3]:
T = np.array([[1,2], [2,4]])
eig_val, eig_vec = np.linalg.eig(T)
print(T)
print(eig_val)
print(eig_vec)

[[1 2]
 [2 4]]
[0. 5.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [4]:
vec1 = np.array([5,10])
vec1 / np.sqrt(125)

array([0.4472136 , 0.89442719])

In [5]:
vec2 = np.array([1,2])
vec2 / np.sqrt(5)

array([0.4472136 , 0.89442719])

In [6]:
T @ vec2

array([ 5, 10])

Decomposition 

In [7]:
eig_val

array([0., 5.])

In [8]:
eig_vec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [9]:
deconstruct = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
deconstruct

array([[1., 2.],
       [2., 4.]])

In [10]:
coba = np.array([[0,-1],
            [1,0]])
coba

array([[ 0, -1],
       [ 1,  0]])

In [11]:
eig_val, eig_vec = np.linalg.eig(coba)

In [12]:
abs(eig_vec)

array([[0.70710678, 0.70710678],
       [0.70710678, 0.70710678]])

In [13]:
abs(eig_val)

array([1., 1.])

Case Study : social media analysis

In [14]:
sc = np.array([[0,.25,0,.5,0,0],
                [0,0,0,0,0,0],
                [.5,.25,0,0,0,.5],
                [.5,.25,0,0,0,.5],
                [0,.25,0,.5,0,0],
                [0,0,0,0,0,0],
])

cari nilai eigen value dan eigen vector

In [15]:
e_val, e_vec = np.linalg.eig(sc)

In [16]:
e_val

array([ 0. ,  0. ,  0.5, -0.5,  0. ,  0. ])

In [17]:
e_vec

array([[ 0.00000000e+000,  0.00000000e+000,  5.00000000e-001,
        -5.00000000e-001, -2.16623325e-276, -2.34960985e-276],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  4.33246650e-276,  0.00000000e+000],
       [ 0.00000000e+000,  1.00000000e+000,  5.00000000e-001,
         5.00000000e-001,  6.00000000e-001,  2.16930458e-001],
       [ 0.00000000e+000,  0.00000000e+000,  5.00000000e-001,
         5.00000000e-001, -2.16623325e-276,  1.10526918e-291],
       [ 1.00000000e+000,  0.00000000e+000,  5.00000000e-001,
        -5.00000000e-001, -8.00000000e-001, -9.76187060e-001],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  2.34960985e-276]])

cari posisi eigen value terbesar

In [18]:
np.argmax(e_val)

2

dari pasangan eigen value terbesar, cari posisi nilai terbesar eigen vektornya

In [19]:
e_vec[2]

array([0.        , 1.        , 0.5       , 0.5       , 0.6       ,
       0.21693046])

In [20]:
np.argmax(e_vec[2])

1