In [76]:
import numpy as np

Vektor = 1 dimensional array

matriks = 2 dimensional array

vektor itu setara Series di pandas. 

matriks itu setara DataFrame atau table di pandas. 

atau matriks itu adalah kumpulan dari vektor dialam array numpy

In [77]:
matriks_a = np.array([[1,2],[3,4],[5,6]])
matriks_a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
matriks_a.shape

(3, 2)

dimensi 
- array / data
- representasi data

|data1|data2|
|---|---|

2 dimensi

|data1|data2|data3|
|---|---|---|

3 dimensi

inverse = apabila bilangan/ matriks dikalikan dengan invers = identitas matriksnya

inverse  A^-1

bila A @ A^-1 maka akan menghasilkan = identitas

In [79]:
matriks_b = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

matriks_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
matriks_b[1]

array([4, 5, 6])

In [81]:
matriks_b[1][2]

6

In [82]:
matriks_b[1,2]

6

In [83]:
matriks_b[:,-1]

array([3, 6, 9])

In [84]:
# ini diambil secara diagonal
np.diag(matriks_b)

array([1, 5, 9])

In [85]:
np.diag(np.diag(matriks_b))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [86]:
# matriks identitas
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [88]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Operasi aritmatika matriks

Penjumlahan

In [89]:
matriks_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
matriks_c = np.array([[1,2,0],
                    [4,1,3],
                    [2,5,0]])
matriks_c

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

In [91]:
# penjumlahan itu elemen wise

matriks_b + matriks_c

array([[ 2,  4,  3],
       [ 8,  6,  9],
       [ 9, 13,  9]])

In [92]:
matriks_b +10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

Pengurangan

In [93]:
# pengurangan dengan elemenwise
matriks_b - matriks_c

array([[0, 0, 3],
       [0, 4, 3],
       [5, 3, 9]])

In [94]:
10 - matriks_b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Pembagian

In [95]:
matriks_c / matriks_b

array([[1.        , 1.        , 0.        ],
       [1.        , 0.2       , 0.5       ],
       [0.28571429, 0.625     , 0.        ]])

In [96]:
matriks_b /2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

Perkalian


In [97]:
# perkalian hadamard product. operasi element wise

matriks_b * matriks_c

array([[ 1,  4,  0],
       [16,  5, 18],
       [14, 40,  0]])

In [98]:
# perkalian dengan skalar
matriks_b * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [99]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
# perkalian hadamard product. operasi element wise
matriks_b * d

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [101]:
# perkalian antar matriks
print(matriks_b)
print(matriks_c)

matriks_b @ matriks_c

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 0]
 [4 1 3]
 [2 5 0]]


array([[15, 19,  6],
       [36, 43, 15],
       [57, 67, 24]])

In [102]:
print(matriks_b)
print(d)
matriks_b @ d

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [103]:
e = np.array([[2,3],
                [4,5],
                [6,7]])

e

array([[2, 3],
       [4, 5],
       [6, 7]])

In [104]:
print(matriks_b)
print(e)
matriks_b @ e


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [4 5]
 [6 7]]


array([[ 28,  34],
       [ 64,  79],
       [100, 124]])

In [105]:
# tidak bisa apabila di balik perkalian dot matriksnya karena bentuk matriksnya tidak memungkinkan
e @ matriks_b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
x = np.array([[3,1,7],
                [4,5,6]])

In [ ]:
y = np.array([[2],[1],[0]])

In [ ]:
z = x @ y
z

array([[ 7],
       [13]])

In [ ]:
z.shape

(2, 1)

## transpose

In [ ]:
matriks_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriks_b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## inverse

In [ ]:
matriks_c

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

In [ ]:
invc = np.linalg.inv(matriks_c)
invc

array([[ 5.        ,  0.        , -2.        ],
       [-2.        ,  0.        ,  1.        ],
       [-6.        ,  0.33333333,  2.33333333]])

In [ ]:
# bila dikalikan dengan matriksnya akan menjadi matriks identitas
matriks_c @ invc

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 1.0000000e+00]])

In [ ]:
# ini adalah matriks identitas
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

INverse hanya bisa dimiliki matriks persegi

singular matrix = determinannya 0 atau tidak punya inverse

ciri2

1. barisnya bisa  kelipatan
2. kombinasi linier dari baris yang lain

In [109]:
matriks_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
# matriks memiliki determinan 0
np.linalg.det(matriks_b)

0.0

In [108]:
# ini contoh singular matriks
np.linalg.inv(matriks_b)

LinAlgError: Singular matrix