In [1]:
import numpy as np

In [4]:
tinggi = [160,172,175,160]
berat = [66,70,80,60]
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

np_tinggi/np_berat

array([2.42424242, 2.45714286, 2.1875    , 2.66666667])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
print(np.arange(3,10,2))

[3 5 7 9]


In [10]:
arr= np.array([1,2,3,4])
arr_new = np.append(arr,[7,8,9])

In [11]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [12]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

# 0 - D / Skalar

In [14]:
arr = np.array(6)
print(arr)

6


In [15]:
arr.ndim
# ndim ini untuk dimensi

0

In [16]:
arr.shape

()

# 1-D/Vektor

In [17]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [18]:
arr.ndim
# ndim ini untuk dimensi

1

In [19]:
arr.shape

(4,)

# 2-D/ Matriks

In [31]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr.ndim

2

In [23]:
arr.shape

(2, 4)

In [25]:
arr = np.array([[[1,2,3,4]]])
arr

array([[[1, 2, 3, 4]]])

In [26]:
arr.ndim

3

In [28]:
arr.shape

(1, 1, 4)

In [29]:

arr.size

4

In [41]:
arr = np.arange(9)
matriks = arr.reshape(3,3)
print(matriks)
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
matriks.ndim

2

In [44]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [45]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [57]:
a3 = a[np.newaxis]
print(a3.shape)
a3

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [61]:
a_e = np.expand_dims(a, axis=1)
a_e.shape
print(a_e)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [64]:
a_e = np.expand_dims(a, axis=0)
print(a_e.shape)
print(a_e)

(1, 6)
[[1 2 3 4 5 6]]


In [78]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a_e2 = np.expand_dims(arr_2d, axis=2)
a_e2.shape

(2, 4, 1)

## soal

In [81]:
arr = np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [82]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [83]:
arr = np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [96]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[0,2])
print(arr[0,1:3])
print(arr[2,2:3])
print(arr[2:4,2])
print(arr[1:2,3])

3
[2 3]
[11]
[11]
[8]


In [105]:
arr = np.array([[1,2,3,4,8,10],[5,6,7,8,70,100],[9,10,11,12,110,120]])
print(arr[:4:2,2])
print(arr[1:2,2:3])
print(arr[arr>=3])

[ 3 11]
[[7]]
[  3   4   8  10   5   6   7   8  70 100   9  10  11  12 110 120]


In [106]:
arr[arr>=3].ndim

1

In [108]:
a_1 = np.array([[1,1],
                [2,2]])
                
a_2 = np.array([[3,3],
                [4,4]])

np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [109]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [133]:
arr_new= np.array([1,2,3,4,5,6,7,8,np.NaN,10,11,12])
new_arr = arr_new.reshape(1,3,-1) # -1 adalah unknown dimension 
new_arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [nan, 10., 11., 12.]]])

In [ ]:
# ravel
# flatten